### ISSUE TITLE
JS scripting for API connection to CoinGecko

### ISSUE THREAD

**Issue by jvesterfelt** [EastonShaum/Group-Project-1#5]
Script that handles logic involved in fetching from the CoinGecko API. (specifics about what we'll be doing should probably be added to this ticket later).

**Comment by EastonShaum** [comment]
I made functions pulling data from the coingecko API. 
coinInfo = all the info about a coin. requires name and date.
trendingCoins = the top seven coins currently and their info
listOfCoins = a list of all the coins
